title: yrhs-dev
subtitle: yrhs-dev's Growth Blog 
description: >- # this means to ignore newlines until "baseurl:"
  Hyunsu Jang(yrhs-dev) is a developer who pursues the convergence of hardware, software & design. 

url: "https://yrhs-dev.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Hardware
      url: /hardware
    - text: Software
      url: /software
    - text: Design
      url: /design
    - text: Gallery
      url: /gallery
    - text: Plan
      url: /Plan
    - text: Contact Me
      url : /contact

# Edit these details

author_logo: profile.png
author: Hyunsu Jang
author_bio: <p>Hello, Welcome to Hyunsu Jang(yrhs-dev)'s Blog. ğŸ˜€<br> I'm a developer who pursues the convergence of hardware, software & design. ğŸ˜<br> Also, I am a undergraduate student at Kyung Hee UniversityğŸ›, Department of IE, EE & CE.<br>My major study is concentrated in Data ScienceğŸ“š and Circuit DesignğŸ”Œ.<br>I am also a research intern at Big Data Lab (Allbigdata) at KyungHee UniversityğŸ›, under the supervision of Prof. ChangHo ChinğŸ§‘ğŸ».<br>My focus area lies in the convergence of HardwareğŸ”Œ, SoftewareğŸ’» & DesignğŸ¨ like AppleğŸ.<br>I like to read booksğŸ“š, go classical music conertğŸ–¼ and be on instagramğŸŒŠ, and I love to collect some information related to A.I.ğŸ§‘, Data ScienceğŸ“š and Circuit DesignğŸ”Œ</p>
author_email: "travel_98@khu.ac.kr"
author_location: Suwon, South Korea
author_website_url: "instagram.com/yrhs.dev/"
author_google_scholar: 
typewrite-text: I'm a developer who pursues the convergence of hardware, software & design. 

author_work_experiences:
            - company_name: Professional Logistician
              company_logo: korea.jpg
              company_url: https://www.epost.go.kr/main.retrieveMainPage.com
              designation: Korea Post
              description: Management of Supply Chain (SCM)
              visibility: true
            - company_name: Arranging documents using Excel
              company_logo: khu_linc.png
              company_url: http://lincplus.khu.ac.kr/
              designation: Kyung Hee University LinC+
              description: Worked on various excel business
              visibility: true

author_ğŸ“education_details:
              - college_logo: khu_kr.png
                college_name: A undergraduate student
                college_url: http://www.khu.ac.kr/
                college_degree: Kyung Hee University
                description:  IE, EE & CE
                visibility: true

author_project_details:
              - project_thumbnail: dust_prediction.png
                project_title: Prediction of Air pollution using deep learning(LSTM) 
                project_description: The project was selected for excellent project in Web&Python Programming class, Kyung Hee University.<br>  Also, the project was selected as an excellent project for SW Convergence Scholarship in SW-Centered Business Group, Kyung Hee University.
                project_url: https://khlug.org/group/50005
                visibility: true
              - project_thumbnail: SMAP.png
                project_title: Prediction of Stock Market Analysis(SMAP) 
                project_description: The project was selected for excellent project in Khlug, Kyung Hee University.
                project_url: https://khlug.org/group/46639
                visibility: true

# social links
twitter_username: yrhs_dev
github_username:  yrhs-dev
facebook_username: yrhs.dev
linkedin_username: yrhs-dev
behance_username: null
instagram_username: yrhs.dev
medium_username: null
telegram_username: null
dribbble_username: yrhs-dev
flickr_username: null

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: yrhs-dev

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: travel_98@khu.ac.kr

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_ğŸ“education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
